# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '04a77614-b0f6-4554-8a65-20f076949a88'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ArmTemplateRG'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: 'projectName ARMDeployment -linkedTemplateUri https://raw.githubusercontent.com/genetru/AzPipe-Repo/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
